### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chjXu** [wangguanan/light-reid#17]
when finish training, there is a error in eval function. 
how to solve it?

Traceback (most recent call last):
  File "main.py", line 60, in <module>
    solver.eval(onebyone=True)
  File "../../lightreid/engine/engine.py", line 277, in eval
    mAP, CMC, ranktime, evaltime = CmcMapEvaluator1b1(metric=metric, mode='inter-camera').compute(
  File "../../lightreid/evaluations/rank/rank_1b1.py", line 45, in __init__
    progressbar.SimpleProgress(format='%(value_s)s/%(max_value_s)s'),
TypeError: __init__() got an unexpected keyword argument 'format'

**Comment by wangguanan** [comment]
the bug has been fixed, please re-pull the repo. thx.
