### ISSUE TITLE
执行lightsearch时报错

### ISSUE THREAD

**Issue by cxh1996** [wangguanan/light-reid#29]
执行CUDA_VISIBLE_DEVICES=1 python main.py --dataset dukemtmcreid --results_dir ./results/dukemtmcreid/ --lightfeat True --lightsearch True报错：

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    light_model=args.lightmodel, light_feat=args.lightfeat, light_search=args.lightsearch)
  File "../../lightreid/engine/engine.py", line 106, in __init__
    self.model.enable_tanh()
  File "/environment/python/versions/miniconda3-4.7.12/envs/lightreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'BaseReIDModel' object has no attribute 'enable_tanh'

**Comment by HowardWang0915** [comment]
您好：我也有遇到以上問題，想請問樓主是如何解決的，謝謝！
