### ISSUE TITLE
base_config_duke_res18_lightmodel_lightfeat.yaml

### ISSUE THREAD

**Issue by HowardWang0915** [wangguanan/light-reid#34]
作者您好：
我想問我在使用bagtricks_buildwithconfigs時使用python train.py --config_file ./configs/base_config_duke_res19_lightmodel_lightfeat.yaml，由於我沒有pretrain的model我將light_model功能關閉，的時候會出現           
```bash
home/pp/anaconda3/envs/lightreid/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    solver.train(eval_freq=10)
  File "../../lightreid/engine/engine.py", line 209, in train
    self.eval(onebyone=False)
  File "../../lightreid/engine/engine.py", line 273, in eval
    query_feats, query_pids, query_camids = self.extract_feats(query_loader, time_meter=time_meter)
  File "../../lightreid/engine/engine.py", line 426, in extract_feats
    feats = self.model(imgs)
  File "/home/pp/anaconda3/envs/lightreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pp/anaconda3/envs/lightreid/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/pp/anaconda3/envs/lightreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../../lightreid/models/architectures/base_arch.py", line 41, in forward
    res = self.head(feats_vec, y)
  File "/home/pp/anaconda3/envs/lightreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../../lightreid/models/heads/code_pyramid.py", line 62, in forward
    binary_codes = neck(feats, use_tanh=use_tanh)
  File "/home/pp/anaconda3/envs/lightreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'use_tanh'
```
這是再有開啟clean engine之下，如果將clean engine關閉會出現
``` bash
/home/pp/anaconda3/envs/lightreid/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    solver = lightreid.build_engine(config)
  File "../../lightreid/build.py", line 50, in build_engine
    **cfg.env, **cfg.lightreid)
  File "../../lightreid/engine/engine.py", line 107, in __init__
    self.model.enable_tanh()
  File "/home/pp/anaconda3/envs/lightreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'BaseReIDModel' object has no attribute 'enable_tanh'
```
我在project之中找不到enable_tanh的function
如果將light model，light feat, light search關閉，則可以正常運作。
還請作者幫忙解答了，謝謝！

**Comment by wangguanan** [comment]
抱歉最近太忙了，没来得及回复。
bug已修复
https://github.com/wangguanan/light-reid/commit/20233c977c5d031987f4ced89da38df6388955d0#diff-0db9d85d18f7ad7eff181bf43620a2550820e926aff04ad0cec8044d4a5a6a3fR108

**Comment by YMMS** [comment]
There are still bugs in BNHead when lightsearch=True in the source code, and the output format does not match the interface for CodePyramid. @wangguanan, could you share the private repository mentioned in https://github.com/wangguanan/light-reid/issues/42? Additionally, the implementation of the DTO does not match the formula (7) (8). Could you please provide some guidance?
